/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AccessoidcApi
 */
@Ignore
public class AccessoidcApiTest {

    private final AccessoidcApi api = new AccessoidcApi();

    /**
     * Redirect/callback URI for processing the result of the OpenId Connect login sequence.
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void oidcCallbackTest() throws Exception {
        api.oidcCallback();

        // TODO: test validations
    }
    /**
     * Retrieves a JWT following a successful login sequence using the configured OpenId Connect provider.
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void oidcExchangeTest() throws Exception {
        String response = api.oidcExchange();

        // TODO: test validations
    }
    /**
     * Performs a logout in the OpenId Provider.
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void oidcLogoutTest() throws Exception {
        api.oidcLogout();

        // TODO: test validations
    }
    /**
     * Redirect/callback URI for processing the result of the OpenId Connect logout sequence.
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void oidcLogoutCallbackTest() throws Exception {
        api.oidcLogoutCallback();

        // TODO: test validations
    }
    /**
     * Initiates a request to authenticate through the configured OpenId Connect provider.
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void oidcRequestTest() throws Exception {
        api.oidcRequest();

        // TODO: test validations
    }
}
