/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client;

import com.github.asamoal.nifi.swagger.client.model.ConnectionEntity;
import com.github.asamoal.nifi.swagger.client.model.ConnectionsEntity;
import com.github.asamoal.nifi.swagger.client.model.ControllerServiceEntity;
import com.github.asamoal.nifi.swagger.client.model.CopySnippetRequestEntity;
import com.github.asamoal.nifi.swagger.client.model.CreateTemplateRequestEntity;
import com.github.asamoal.nifi.swagger.client.model.DropRequestEntity;
import java.io.File;
import com.github.asamoal.nifi.swagger.client.model.FlowComparisonEntity;
import com.github.asamoal.nifi.swagger.client.model.FlowEntity;
import com.github.asamoal.nifi.swagger.client.model.FunnelEntity;
import com.github.asamoal.nifi.swagger.client.model.FunnelsEntity;
import com.github.asamoal.nifi.swagger.client.model.InputPortsEntity;
import com.github.asamoal.nifi.swagger.client.model.InstantiateTemplateRequestEntity;
import com.github.asamoal.nifi.swagger.client.model.LabelEntity;
import com.github.asamoal.nifi.swagger.client.model.LabelsEntity;
import com.github.asamoal.nifi.swagger.client.model.OutputPortsEntity;
import com.github.asamoal.nifi.swagger.client.model.PortEntity;
import com.github.asamoal.nifi.swagger.client.model.ProcessGroupEntity;
import com.github.asamoal.nifi.swagger.client.model.ProcessGroupImportEntity;
import com.github.asamoal.nifi.swagger.client.model.ProcessGroupReplaceRequestEntity;
import com.github.asamoal.nifi.swagger.client.model.ProcessGroupsEntity;
import com.github.asamoal.nifi.swagger.client.model.ProcessorEntity;
import com.github.asamoal.nifi.swagger.client.model.ProcessorsEntity;
import com.github.asamoal.nifi.swagger.client.model.RemoteProcessGroupEntity;
import com.github.asamoal.nifi.swagger.client.model.RemoteProcessGroupsEntity;
import com.github.asamoal.nifi.swagger.client.model.TemplateEntity;
import com.github.asamoal.nifi.swagger.client.model.VariableRegistryEntity;
import com.github.asamoal.nifi.swagger.client.model.VariableRegistryUpdateRequestEntity;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ProcessGroupsApi
 */
@Ignore
public class ProcessGroupsApiTest {

    private final ProcessGroupsApi api = new ProcessGroupsApi();

    /**
     * Copies a snippet and discards it.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void copySnippetTest() throws Exception {
        CopySnippetRequestEntity body = null;
        String id = null;
        FlowEntity response = api.copySnippet(body, id);

        // TODO: test validations
    }
    /**
     * Creates a connection
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createConnectionTest() throws Exception {
        ConnectionEntity body = null;
        String id = null;
        ConnectionEntity response = api.createConnection(body, id);

        // TODO: test validations
    }
    /**
     * Creates a new controller service
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createControllerServiceTest() throws Exception {
        ControllerServiceEntity body = null;
        String id = null;
        ControllerServiceEntity response = api.createControllerService(body, id);

        // TODO: test validations
    }
    /**
     * Creates a request to drop all flowfiles of all connection queues in this process group.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createEmptyAllConnectionsRequestTest() throws Exception {
        String id = null;
        DropRequestEntity response = api.createEmptyAllConnectionsRequest(id);

        // TODO: test validations
    }
    /**
     * Creates a funnel
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createFunnelTest() throws Exception {
        FunnelEntity body = null;
        String id = null;
        FunnelEntity response = api.createFunnel(body, id);

        // TODO: test validations
    }
    /**
     * Creates an input port
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createInputPortTest() throws Exception {
        PortEntity body = null;
        String id = null;
        PortEntity response = api.createInputPort(body, id);

        // TODO: test validations
    }
    /**
     * Creates a label
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createLabelTest() throws Exception {
        LabelEntity body = null;
        String id = null;
        LabelEntity response = api.createLabel(body, id);

        // TODO: test validations
    }
    /**
     * Creates an output port
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createOutputPortTest() throws Exception {
        PortEntity body = null;
        String id = null;
        PortEntity response = api.createOutputPort(body, id);

        // TODO: test validations
    }
    /**
     * Creates a process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createProcessGroupTest() throws Exception {
        ProcessGroupEntity body = null;
        String id = null;
        ProcessGroupEntity response = api.createProcessGroup(body, id);

        // TODO: test validations
    }
    /**
     * Creates a new processor
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createProcessorTest() throws Exception {
        ProcessorEntity body = null;
        String id = null;
        ProcessorEntity response = api.createProcessor(body, id);

        // TODO: test validations
    }
    /**
     * Creates a new process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createRemoteProcessGroupTest() throws Exception {
        RemoteProcessGroupEntity body = null;
        String id = null;
        RemoteProcessGroupEntity response = api.createRemoteProcessGroup(body, id);

        // TODO: test validations
    }
    /**
     * Creates a template and discards the specified snippet.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createTemplateTest() throws Exception {
        CreateTemplateRequestEntity body = null;
        String id = null;
        TemplateEntity response = api.createTemplate(body, id);

        // TODO: test validations
    }
    /**
     * Deletes the Replace Request with the given ID
     *
     * Deletes the Replace Request with the given ID. After a request is created via a POST to /process-groups/{id}/replace-requests, it is expected that the client will properly clean up the request by DELETE&#x27;ing it, once the Replace process has completed. If the request is deleted before the request completes, then the Replace request will finish the step that it is currently performing and then will cancel any subsequent steps. Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteReplaceProcessGroupRequestTest() throws Exception {
        String id = null;
        Boolean disconnectedNodeAcknowledged = null;
        ProcessGroupReplaceRequestEntity response = api.deleteReplaceProcessGroupRequest(id, disconnectedNodeAcknowledged);

        // TODO: test validations
    }
    /**
     * Deletes an update request for a process group&#x27;s variable registry. If the request is not yet complete, it will automatically be cancelled.
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteVariableRegistryUpdateRequestTest() throws Exception {
        String groupId = null;
        String updateId = null;
        Boolean disconnectedNodeAcknowledged = null;
        VariableRegistryUpdateRequestEntity response = api.deleteVariableRegistryUpdateRequest(groupId, updateId, disconnectedNodeAcknowledged);

        // TODO: test validations
    }
    /**
     * Gets a process group for download
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void exportProcessGroupTest() throws Exception {
        String id = null;
        Boolean includeReferencedServices = null;
        String response = api.exportProcessGroup(id, includeReferencedServices);

        // TODO: test validations
    }
    /**
     * Gets all connections
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getConnectionsTest() throws Exception {
        String id = null;
        ConnectionsEntity response = api.getConnections(id);

        // TODO: test validations
    }
    /**
     * Gets the current status of a drop all flowfiles request.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getDropAllFlowfilesRequestTest() throws Exception {
        String id = null;
        String dropRequestId = null;
        DropRequestEntity response = api.getDropAllFlowfilesRequest(id, dropRequestId);

        // TODO: test validations
    }
    /**
     * Gets all funnels
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFunnelsTest() throws Exception {
        String id = null;
        FunnelsEntity response = api.getFunnels(id);

        // TODO: test validations
    }
    /**
     * Gets all input ports
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInputPortsTest() throws Exception {
        String id = null;
        InputPortsEntity response = api.getInputPorts(id);

        // TODO: test validations
    }
    /**
     * Gets all labels
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getLabelsTest() throws Exception {
        String id = null;
        LabelsEntity response = api.getLabels(id);

        // TODO: test validations
    }
    /**
     * Gets a list of local modifications to the Process Group since it was last synchronized with the Flow Registry
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getLocalModificationsTest() throws Exception {
        String id = null;
        FlowComparisonEntity response = api.getLocalModifications(id);

        // TODO: test validations
    }
    /**
     * Gets all output ports
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOutputPortsTest() throws Exception {
        String id = null;
        OutputPortsEntity response = api.getOutputPorts(id);

        // TODO: test validations
    }
    /**
     * Gets a process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProcessGroupTest() throws Exception {
        String id = null;
        ProcessGroupEntity response = api.getProcessGroup(id);

        // TODO: test validations
    }
    /**
     * Gets all process groups
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProcessGroupsTest() throws Exception {
        String id = null;
        ProcessGroupsEntity response = api.getProcessGroups(id);

        // TODO: test validations
    }
    /**
     * Gets all processors
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProcessorsTest() throws Exception {
        String id = null;
        Boolean includeDescendantGroups = null;
        ProcessorsEntity response = api.getProcessors(id, includeDescendantGroups);

        // TODO: test validations
    }
    /**
     * Gets all remote process groups
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRemoteProcessGroupsTest() throws Exception {
        String id = null;
        RemoteProcessGroupsEntity response = api.getRemoteProcessGroups(id);

        // TODO: test validations
    }
    /**
     * Returns the Replace Request with the given ID
     *
     * Returns the Replace Request with the given ID. Once a Replace Request has been created by performing a POST to /process-groups/{id}/replace-requests, that request can subsequently be retrieved via this endpoint, and the request that is fetched will contain the updated state, such as percent complete, the current state of the request, and any failures. Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getReplaceProcessGroupRequestTest() throws Exception {
        String id = null;
        ProcessGroupReplaceRequestEntity response = api.getReplaceProcessGroupRequest(id);

        // TODO: test validations
    }
    /**
     * Gets a process group&#x27;s variable registry
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getVariableRegistryTest() throws Exception {
        String id = null;
        Boolean includeAncestorGroups = null;
        VariableRegistryEntity response = api.getVariableRegistry(id, includeAncestorGroups);

        // TODO: test validations
    }
    /**
     * Gets a process group&#x27;s variable registry
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getVariableRegistryUpdateRequestTest() throws Exception {
        String groupId = null;
        String updateId = null;
        VariableRegistryUpdateRequestEntity response = api.getVariableRegistryUpdateRequest(groupId, updateId);

        // TODO: test validations
    }
    /**
     * Imports a specified process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void importProcessGroupTest() throws Exception {
        String id = null;
        ProcessGroupEntity response = api.importProcessGroup(id);

        // TODO: test validations
    }
    /**
     * Imports a template
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void importTemplateTest() throws Exception {
        String id = null;
        TemplateEntity response = api.importTemplate(id);

        // TODO: test validations
    }
    /**
     * Initiate the Replace Request of a Process Group with the given ID
     *
     * This will initiate the action of replacing a process group with the given process group. This can be a lengthy process, as it will stop any Processors and disable any Controller Services necessary to perform the action and then restart them. As a result, the endpoint will immediately return a ProcessGroupReplaceRequestEntity, and the process of replacing the flow will occur asynchronously in the background. The client may then periodically poll the status of the request by issuing a GET request to /process-groups/replace-requests/{requestId}. Once the request is completed, the client is expected to issue a DELETE request to /process-groups/replace-requests/{requestId}. Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void initiateReplaceProcessGroupTest() throws Exception {
        ProcessGroupImportEntity body = null;
        String id = null;
        ProcessGroupReplaceRequestEntity response = api.initiateReplaceProcessGroup(body, id);

        // TODO: test validations
    }
    /**
     * Instantiates a template
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void instantiateTemplateTest() throws Exception {
        InstantiateTemplateRequestEntity body = null;
        String id = null;
        FlowEntity response = api.instantiateTemplate(body, id);

        // TODO: test validations
    }
    /**
     * Cancels and/or removes a request to drop all flowfiles.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void removeDropRequestTest() throws Exception {
        String id = null;
        String dropRequestId = null;
        DropRequestEntity response = api.removeDropRequest(id, dropRequestId);

        // TODO: test validations
    }
    /**
     * Deletes a process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void removeProcessGroupTest() throws Exception {
        String id = null;
        String version = null;
        String clientId = null;
        Boolean disconnectedNodeAcknowledged = null;
        ProcessGroupEntity response = api.removeProcessGroup(id, version, clientId, disconnectedNodeAcknowledged);

        // TODO: test validations
    }
    /**
     * Replace Process Group contents with the given ID with the specified Process Group contents
     *
     * This endpoint is used for replication within a cluster, when replacing a flow with a new flow. It expects that the flow beingreplaced is not under version control and that the given snapshot will not modify any Processor that is currently running or any Controller Service that is enabled. Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void replaceProcessGroupTest() throws Exception {
        ProcessGroupImportEntity body = null;
        String id = null;
        ProcessGroupImportEntity response = api.replaceProcessGroup(body, id);

        // TODO: test validations
    }
    /**
     * Submits a request to update a process group&#x27;s variable registry
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void submitUpdateVariableRegistryRequestTest() throws Exception {
        VariableRegistryEntity body = null;
        String id = null;
        VariableRegistryUpdateRequestEntity response = api.submitUpdateVariableRegistryRequest(body, id);

        // TODO: test validations
    }
    /**
     * Updates a process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateProcessGroupTest() throws Exception {
        ProcessGroupEntity body = null;
        String id = null;
        ProcessGroupEntity response = api.updateProcessGroup(body, id);

        // TODO: test validations
    }
    /**
     * Updates the contents of a Process Group&#x27;s variable Registry
     *
     * Note: This endpoint is subject to change as NiFi and it&#x27;s REST API evolve.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateVariableRegistryTest() throws Exception {
        VariableRegistryEntity body = null;
        String id = null;
        VariableRegistryEntity response = api.updateVariableRegistry(body, id);

        // TODO: test validations
    }
    /**
     * Uploads a versioned flow definition and creates a process group
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadProcessGroupTest() throws Exception {
        String id = null;
        ProcessGroupEntity response = api.uploadProcessGroup(id);

        // TODO: test validations
    }
    /**
     * Uploads a template
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadTemplateTest() throws Exception {
        File template = null;
        String id = null;
        TemplateEntity response = api.uploadTemplate(template, id);

        // TODO: test validations
    }
}
