/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AccessStatusDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T17:38:07.775342+02:00[Europe/Berlin]")
public class AccessStatusDTO {
  @SerializedName("identity")
  private String identity = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("message")
  private String message = null;

  public AccessStatusDTO identity(String identity) {
    this.identity = identity;
    return this;
  }

   /**
   * The user identity.
   * @return identity
  **/
  @Schema(description = "The user identity.")
  public String getIdentity() {
    return identity;
  }

  public void setIdentity(String identity) {
    this.identity = identity;
  }

  public AccessStatusDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The user access status.
   * @return status
  **/
  @Schema(description = "The user access status.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public AccessStatusDTO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Additional details about the user access status.
   * @return message
  **/
  @Schema(description = "Additional details about the user access status.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessStatusDTO accessStatusDTO = (AccessStatusDTO) o;
    return Objects.equals(this.identity, accessStatusDTO.identity) &&
        Objects.equals(this.status, accessStatusDTO.status) &&
        Objects.equals(this.message, accessStatusDTO.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identity, status, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessStatusDTO {\n");
    
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
