/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.asamoal.nifi.swagger.client.model.BundleDTO;
import com.github.asamoal.nifi.swagger.client.model.ClassLoaderDiagnosticsDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ClassLoaderDiagnosticsDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T17:38:07.775342+02:00[Europe/Berlin]")
public class ClassLoaderDiagnosticsDTO {
  @SerializedName("bundle")
  private BundleDTO bundle = null;

  @SerializedName("parentClassLoader")
  private ClassLoaderDiagnosticsDTO parentClassLoader = null;

  public ClassLoaderDiagnosticsDTO bundle(BundleDTO bundle) {
    this.bundle = bundle;
    return this;
  }

   /**
   * Get bundle
   * @return bundle
  **/
  @Schema(description = "")
  public BundleDTO getBundle() {
    return bundle;
  }

  public void setBundle(BundleDTO bundle) {
    this.bundle = bundle;
  }

  public ClassLoaderDiagnosticsDTO parentClassLoader(ClassLoaderDiagnosticsDTO parentClassLoader) {
    this.parentClassLoader = parentClassLoader;
    return this;
  }

   /**
   * Get parentClassLoader
   * @return parentClassLoader
  **/
  @Schema(description = "")
  public ClassLoaderDiagnosticsDTO getParentClassLoader() {
    return parentClassLoader;
  }

  public void setParentClassLoader(ClassLoaderDiagnosticsDTO parentClassLoader) {
    this.parentClassLoader = parentClassLoader;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassLoaderDiagnosticsDTO classLoaderDiagnosticsDTO = (ClassLoaderDiagnosticsDTO) o;
    return Objects.equals(this.bundle, classLoaderDiagnosticsDTO.bundle) &&
        Objects.equals(this.parentClassLoader, classLoaderDiagnosticsDTO.parentClassLoader);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundle, parentClassLoader);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassLoaderDiagnosticsDTO {\n");
    
    sb.append("    bundle: ").append(toIndentedString(bundle)).append("\n");
    sb.append("    parentClassLoader: ").append(toIndentedString(parentClassLoader)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
