/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.asamoal.nifi.swagger.client.model.ParameterContextEntity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ParameterContextsEntity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T17:38:07.775342+02:00[Europe/Berlin]")
public class ParameterContextsEntity {
  @SerializedName("parameterContexts")
  private List<ParameterContextEntity> parameterContexts = null;

  @SerializedName("currentTime")
  private String currentTime = null;

  public ParameterContextsEntity parameterContexts(List<ParameterContextEntity> parameterContexts) {
    this.parameterContexts = parameterContexts;
    return this;
  }

  public ParameterContextsEntity addParameterContextsItem(ParameterContextEntity parameterContextsItem) {
    if (this.parameterContexts == null) {
      this.parameterContexts = new ArrayList<ParameterContextEntity>();
    }
    this.parameterContexts.add(parameterContextsItem);
    return this;
  }

   /**
   * The Parameter Contexts
   * @return parameterContexts
  **/
  @Schema(description = "The Parameter Contexts")
  public List<ParameterContextEntity> getParameterContexts() {
    return parameterContexts;
  }

  public void setParameterContexts(List<ParameterContextEntity> parameterContexts) {
    this.parameterContexts = parameterContexts;
  }

  public ParameterContextsEntity currentTime(String currentTime) {
    this.currentTime = currentTime;
    return this;
  }

   /**
   * The current time on the system.
   * @return currentTime
  **/
  @Schema(description = "The current time on the system.")
  public String getCurrentTime() {
    return currentTime;
  }

  public void setCurrentTime(String currentTime) {
    this.currentTime = currentTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParameterContextsEntity parameterContextsEntity = (ParameterContextsEntity) o;
    return Objects.equals(this.parameterContexts, parameterContextsEntity.parameterContexts) &&
        Objects.equals(this.currentTime, parameterContextsEntity.currentTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameterContexts, currentTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParameterContextsEntity {\n");
    
    sb.append("    parameterContexts: ").append(toIndentedString(parameterContexts)).append("\n");
    sb.append("    currentTime: ").append(toIndentedString(currentTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
