/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.asamoal.nifi.swagger.client.model.NodeReplayLastEventSnapshotDTO;
import com.github.asamoal.nifi.swagger.client.model.ReplayLastEventSnapshotDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ReplayLastEventResponseEntity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T17:38:07.775342+02:00[Europe/Berlin]")
public class ReplayLastEventResponseEntity {
  @SerializedName("componentId")
  private String componentId = null;

  /**
   * Which nodes were requested to replay their last provenance event.
   */
  @JsonAdapter(NodesEnum.Adapter.class)
  public enum NodesEnum {
    ALL("ALL"),
    PRIMARY("PRIMARY");

    private String value;

    NodesEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static NodesEnum fromValue(String input) {
      for (NodesEnum b : NodesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<NodesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NodesEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public NodesEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return NodesEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("nodes")
  private NodesEnum nodes = null;

  @SerializedName("aggregateSnapshot")
  private ReplayLastEventSnapshotDTO aggregateSnapshot = null;

  @SerializedName("nodeSnapshots")
  private List<NodeReplayLastEventSnapshotDTO> nodeSnapshots = null;

  public ReplayLastEventResponseEntity componentId(String componentId) {
    this.componentId = componentId;
    return this;
  }

   /**
   * The UUID of the component whose last event should be replayed.
   * @return componentId
  **/
  @Schema(description = "The UUID of the component whose last event should be replayed.")
  public String getComponentId() {
    return componentId;
  }

  public void setComponentId(String componentId) {
    this.componentId = componentId;
  }

  public ReplayLastEventResponseEntity nodes(NodesEnum nodes) {
    this.nodes = nodes;
    return this;
  }

   /**
   * Which nodes were requested to replay their last provenance event.
   * @return nodes
  **/
  @Schema(description = "Which nodes were requested to replay their last provenance event.")
  public NodesEnum getNodes() {
    return nodes;
  }

  public void setNodes(NodesEnum nodes) {
    this.nodes = nodes;
  }

  public ReplayLastEventResponseEntity aggregateSnapshot(ReplayLastEventSnapshotDTO aggregateSnapshot) {
    this.aggregateSnapshot = aggregateSnapshot;
    return this;
  }

   /**
   * Get aggregateSnapshot
   * @return aggregateSnapshot
  **/
  @Schema(description = "")
  public ReplayLastEventSnapshotDTO getAggregateSnapshot() {
    return aggregateSnapshot;
  }

  public void setAggregateSnapshot(ReplayLastEventSnapshotDTO aggregateSnapshot) {
    this.aggregateSnapshot = aggregateSnapshot;
  }

  public ReplayLastEventResponseEntity nodeSnapshots(List<NodeReplayLastEventSnapshotDTO> nodeSnapshots) {
    this.nodeSnapshots = nodeSnapshots;
    return this;
  }

  public ReplayLastEventResponseEntity addNodeSnapshotsItem(NodeReplayLastEventSnapshotDTO nodeSnapshotsItem) {
    if (this.nodeSnapshots == null) {
      this.nodeSnapshots = new ArrayList<NodeReplayLastEventSnapshotDTO>();
    }
    this.nodeSnapshots.add(nodeSnapshotsItem);
    return this;
  }

   /**
   * The node-wise results
   * @return nodeSnapshots
  **/
  @Schema(description = "The node-wise results")
  public List<NodeReplayLastEventSnapshotDTO> getNodeSnapshots() {
    return nodeSnapshots;
  }

  public void setNodeSnapshots(List<NodeReplayLastEventSnapshotDTO> nodeSnapshots) {
    this.nodeSnapshots = nodeSnapshots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplayLastEventResponseEntity replayLastEventResponseEntity = (ReplayLastEventResponseEntity) o;
    return Objects.equals(this.componentId, replayLastEventResponseEntity.componentId) &&
        Objects.equals(this.nodes, replayLastEventResponseEntity.nodes) &&
        Objects.equals(this.aggregateSnapshot, replayLastEventResponseEntity.aggregateSnapshot) &&
        Objects.equals(this.nodeSnapshots, replayLastEventResponseEntity.nodeSnapshots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(componentId, nodes, aggregateSnapshot, nodeSnapshots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplayLastEventResponseEntity {\n");
    
    sb.append("    componentId: ").append(toIndentedString(componentId)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("    aggregateSnapshot: ").append(toIndentedString(aggregateSnapshot)).append("\n");
    sb.append("    nodeSnapshots: ").append(toIndentedString(nodeSnapshots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
