/*
 * NiFi Rest API
 * The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.
 *
 * OpenAPI spec version: 1.20.0
 * Contact: dev@nifi.apache.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.asamoal.nifi.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.asamoal.nifi.swagger.client.model.RevisionDTO;
import com.github.asamoal.nifi.swagger.client.model.VariableRegistryUpdateRequestDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * VariableRegistryUpdateRequestEntity
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-04-12T17:38:07.775342+02:00[Europe/Berlin]")
public class VariableRegistryUpdateRequestEntity {
  @SerializedName("request")
  private VariableRegistryUpdateRequestDTO request = null;

  @SerializedName("processGroupRevision")
  private RevisionDTO processGroupRevision = null;

  public VariableRegistryUpdateRequestEntity request(VariableRegistryUpdateRequestDTO request) {
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @Schema(description = "")
  public VariableRegistryUpdateRequestDTO getRequest() {
    return request;
  }

  public void setRequest(VariableRegistryUpdateRequestDTO request) {
    this.request = request;
  }

  public VariableRegistryUpdateRequestEntity processGroupRevision(RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
    return this;
  }

   /**
   * Get processGroupRevision
   * @return processGroupRevision
  **/
  @Schema(description = "")
  public RevisionDTO getProcessGroupRevision() {
    return processGroupRevision;
  }

  public void setProcessGroupRevision(RevisionDTO processGroupRevision) {
    this.processGroupRevision = processGroupRevision;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableRegistryUpdateRequestEntity variableRegistryUpdateRequestEntity = (VariableRegistryUpdateRequestEntity) o;
    return Objects.equals(this.request, variableRegistryUpdateRequestEntity.request) &&
        Objects.equals(this.processGroupRevision, variableRegistryUpdateRequestEntity.processGroupRevision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(request, processGroupRevision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableRegistryUpdateRequestEntity {\n");
    
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    processGroupRevision: ").append(toIndentedString(processGroupRevision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
